# Generated by Django 4.2 on 2023-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_result_gambar_alter_proyek_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyek",
            name="gambar3",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="proyek",
            name="gambar4",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
