# Generated by Django 4.2 on 2023-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=15)),
                ("certifier", models.CharField(max_length=50)),
                ("finish", models.DateField(default="2000-03-03")),
            ],
        ),
        migrations.CreateModel(
            name="projectExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=50)),
                ("background", models.CharField(max_length=500)),
                ("finish", models.DateField()),
                ("jobdesk1", models.TextField(blank=True)),
                ("jobdesk2", models.TextField(blank=True)),
                ("jobdesk3", models.TextField(blank=True)),
                ("jobdesk4", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="school",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=25)),
                ("college", models.CharField(max_length=50)),
                ("finish", models.DateField(default="2000-03-03")),
            ],
        ),
        migrations.CreateModel(
            name="workExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=50)),
                ("finish", models.DateField()),
                ("jobdesk1", models.TextField(blank=True)),
                ("jobdesk2", models.TextField(blank=True)),
                ("jobdesk3", models.TextField(blank=True)),
                ("jobdesk4", models.TextField(blank=True)),
            ],
        ),
    ]
