# Generated by Django 4.2 on 2023-12-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="ability",
            field=models.CharField(default="s", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(default="sa", upload_to=""),
            preserve_default=False,
        ),
    ]
