# Generated by Django 4.2 on 2023-12-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skill", "0002_skill_ability_skill_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="ability",
        ),
    ]
